Add lastEventId option to Twig extension
symfony/mercure pull request #72
Opened 2021-11-08 20:43 UTC by chrishemmings

Allow the option `lastEventId` to be passed into the `mercure()` Twig extension options, which then sets `Last-Event-ID` into the subscriber url.

2021-11-23 21:27 UTC, dunglas requested changes
Good idea! Could you also document this new option in the PHPDoc, please?

2021-11-23 21:27 UTC, dunglas commented on src/Twig/MercureExtension.php
> +        if (isset($options['lastEventId']) && '' !== (string) $options['lastEventId']) {
```suggestion
        if ('' !== $options['lastEventId'] ?? '') {
```

2021-11-23 21:27 UTC, dunglas commented on src/Twig/MercureExtension.php
> +            $url .= '&Last-Event-ID='.rawurlencode((string) $options['lastEventId']);
```suggestion
            $url .= '&Last-Event-ID='.rawurlencode($options['lastEventId']);
```

2021-11-24 09:55 UTC, chrishemmings commented
Thanks for the suggestions @dunglas , they have been implemented.

2021-11-25 10:04 UTC, dunglas approved these changes

2021-11-25 10:04 UTC, merged

2021-11-25 10:04 UTC, dunglas commented
Thank you @chrishemmings

2021-11-25 11:59 UTC, chrishemmings commented
Pleasure, thanks for all your hard work @dunglas 👍